# Generated by Django 5.1.1 on 2024-09-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participant', models.IntegerField()),
                ('sydney_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer', models.CharField(max_length=50)),
                ('participant', models.IntegerField()),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=100)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_answer', to='assessment.answer')),
                ('assessment_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentarea')),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.award')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.class')),
                ('correct_answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_correct_answer', to='assessment.answer')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.subject')),
            ],
        ),
    ]
