# Generated by Django 5.1.1 on 2024-09-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='assessment_area_id',
            new_name='assessment_area',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='award_id',
            new_name='award',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='class_id',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='correct_answer_id',
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_correct_answer', to='assessment.answer'),
        ),
    ]
