# Generated by Django 5.1.1 on 2024-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_answer_id_summary_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
    ]
